### ISSUE TITLE
Update AutomaticContainerRegistration attributes

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp#25]
# Descriptions
DryIoC is by default only able to construct classes that have a single constructor. To get pas this the entire container can be set to work in multi-constructor mode or each class that have multiple constructors can be registered as such (See [here](https://bitbucket.org/dadhi/dryioc/wiki/SelectConstructorOrFactoryMethod#markdown-header-multiple-constructors))
To allow automatic registration to know if such a style of registration is needed expand the AutomaticContainerRegistrationBaseAttribute to hold a boolean value that indicate if this is required. Containers that does not need this can simply ignore this value when registering services upstream.

# Tasks
- [x] Add MultipleConstructors property to AutomaticContainerRegistrationBaseAttribute
- [x] Update AutomaticContainerRegistrationBaseAttribute constructor to include the multipleConstructors parameter
- [x] Update AutomaticConcretionContainerRegistrationAttribute to include a constructor that include the multipleConstructors parameter
- [x] Update AutomaticContainerRegistrationAttribute to include a constructor that include the multipleConstructors parameter
