### ISSUE TITLE
General Maintanance

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp#69]
# Description
Some general maintenance tasks to keep VaraniumSharp up to date and easy to maintain.

# Tasks
- [x] Update CakeScripts
- [x] Pin Cake version to the latest version of Cake
- [x] Replace code coverage with AltCover
- [x] Update dependencies
- [x] Remove Paket as it is no longer used
- [x] Update nuspec file (replace obsolete entries)
- [x] Update DocFX.json to point to correct MSDN location (as per new CakeScripts)
- [x] Check and clean code documentation warnings
