### ISSUE TITLE
Auto-resolve on startup

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp#80]
# Description
Currently some classes (notably singletons) need to be "initialized" (resolved) during startup. Currently this is handled client side but should preferably be integrated into VaraniumSharp.

# Tasks
- [x] Expand auto injection attributes to allow setting auto-startup resolve value
- [x] Add logic to handle auto-startup resolve
- [x] Allow ability to enable auto-startup resolve when setting up the container
