### ISSUE TITLE
Update nuspec

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp#91]
# Description
Update the nuspec file to address a few issues.

# Tasks
- [x] Update readme file
- [x] Fix issue with SourceLink
- [x] Make CI build deterministic
